# Site settings
title: hyper
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://hyper.rs" # the base hostname & protocol for your site

defaults:
  -
    scope:
      path: "_guides"
      type: "guides"
    values:
      layout: "guide"

collections:
  guides:
    permalink: /:collection/:path/
    output: true

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge

docs_url: https://docs.rs/hyper/*
futures_url: https://docs.rs/futures/*
tokio_core_url: https://docs.rs/tokio-core/*
hyper_tls_url: https://docs.rs/hyper-tls/*
