# Site settings
title: hyper
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://hyper.rs" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge
